# Generated by Django 4.2.4 on 2023-09-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EmpDepartment',
            field=models.CharField(default='Select Department', max_length=100),
        ),
    ]
