# Generated by Django 4.2.4 on 2023-09-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDAPP', '0003_alter_employee_empdepartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpEmail',
            field=models.EmailField(max_length=50),
        ),
    ]
