# Generated by Django 4.2.4 on 2023-09-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUDAPP', '0016_remove_employee_empgender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='EmpGender',
            field=models.CharField(default='Select gender', max_length=225),
        ),
    ]
