# Generated by Django 4.2.4 on 2023-09-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_empdob_department_empmannameemail_and_more'),
        ('CRUDAPP', '0021_alter_employee_empgender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='EmpDepartment',
        ),
        migrations.AddField(
            model_name='employee',
            name='EmpDepartment',
            field=models.ManyToManyField(to='department.department'),
        ),
    ]
