# Generated by Django 4.2.4 on 2023-09-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_id', models.CharField(max_length=2)),
                ('des_name', models.CharField(max_length=20)),
            ],
        ),
    ]
