# Generated by Django 4.2.4 on 2023-09-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='des_id',
            field=models.CharField(max_length=5),
        ),
    ]
