# Generated by Django 4.2.4 on 2023-09-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0002_alter_designation_des_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designation',
            name='des_id',
        ),
        migrations.AlterField(
            model_name='designation',
            name='des_name',
            field=models.CharField(max_length=255),
        ),
    ]
