# Generated by Django 4.2.4 on 2023-09-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpDept', models.CharField(max_length=50)),
                ('EmpManName', models.CharField(max_length=100)),
                ('EmpPhone', models.CharField(max_length=10)),
                ('EmpSalary', models.CharField(max_length=8)),
            ],
        ),
    ]
