# Generated by Django 4.2.4 on 2023-09-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='EmpDob',
            field=models.CharField(default='fghh', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='EmpManNameEmail',
            field=models.EmailField(default='hhh', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='EmpSalary',
            field=models.CharField(max_length=10),
        ),
    ]
